## Get list users
GET http://api.nestjs.localhost/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc3Yjc1ODBhLWY5MjctNGMwZS04M2I1LWY0NGU0OTVkNzY3OSIsImlhdCI6MTYzMzc5NDk0OSwiZXhwIjoxNjMzODgxMzQ5fQ.LnA-tLZxF-vLzERstB1Ig91Z4p2XFWblV0UZlbFpK-E

