## Get list users
GET http://api.nestjs.localhost/users?page=1&limit=120 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU5Njc5MTI3LWU4YzUtNGFmMi05ODE3LWY4OTgzYjE0MzI1MyIsImlhdCI6MTYzMzgwMjQ4MiwiZXhwIjoxNjMzODg4ODgyfQ.u-dXwYiTq98CDWNluXhbnprlj0Ob8l7bsULCB8Oeryk

