version: '3.8'

services:
  caddy:
    image: caddy/caddy:2.4.5-alpine
    container_name: ${APP_NAME?APP_NAME is required}-caddy
    restart: unless-stopped
    environment:
      - DOMAIN=${DOMAIN?DOMAIN is required}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/${NODE_ENV}/Caddyfile:/etc/caddy/Caddyfile

  backend:
    container_name: ${APP_NAME?APP_NAME is required}-backend
